### PR TITLE
WIP: PyTorch-backed forward simulation

### PR DESCRIPTION
**Pull request by rileyjmurray**
### PR Status
Jan 17: Just creating this to share WIP. Nothing useful as of yet.

### CODE REVIEW

**Comment by sserita** [comment]
If this is WIP, can we keep it as a draft? While in draft mode, it does not assign reviewers/auto-request reviews from code owners, so that seems like the best workflow for not overloading email inboxes while something is not ready for review yet.

**Comment by rileyjmurray** [comment]
@sserita, marked! Sorry. I'm not used to the formal draft feature.

Can you remove the reviewers who were already assigned? GitHub says it'll keep pinging them whenever I update this. If you don't see how do that then I can close and open a new PR.

**Comment by rileyjmurray** [comment]
Superseded by #390.

**Comment by sserita** [comment]
No worries! Reviewers can turn off the notifications themselves and/or remove themselves, but I think the new issue is cleaner - that way, I'll make sure to get the emails whenever you turn it into not draft mode :)

**Pull request closed without merging**
